export const CONFIG = Object.freeze({
    DEFAULT_CANVAS_SIZE: 800,
    DEFAULT_VISIBLE_GRID_SIZE: 80,
    DEFAULT_WORLD_SIZE: 240,
    WORLD_SIZE_MULTIPLIER: 3,
    DEFAULT_ZOOM_LEVEL: 1,
    MIN_ZOOM_LEVEL: 0.375,
    MAX_ZOOM_LEVEL: 1,
    PINCH_ZOOM_SMOOTHING: 0.24,
    PINCH_ZOOM_APPLY_STEP: 0.004,
    WHEEL_ZOOM_STEP: 0.025,
    PAN_DRAG_THRESHOLD_PX: 7,

    MIN_CANVAS_SIZE: 200,
    RECOMMENDED_MAX_CANVAS_SIZE: 1200,
    MAX_CANVAS_SIZE: 2000,
    MIN_VISIBLE_GRID_SIZE: 6,
    RECOMMENDED_MAX_VISIBLE_GRID_SIZE: 160,
    MAX_VISIBLE_GRID_SIZE: 240,
    MIN_WORLD_SIZE: 40,
    RECOMMENDED_MAX_WORLD_SIZE: 1000,
    MAX_WORLD_SIZE: 2000,
    MINIMAP_REDRAW_THROTTLE_MS: 33,

    DESKTOP_MIN_CELL_REM: 0.75,
    TOUCH_MIN_CELL_REM: 1.125,

    ANIMATION_DELAY: 100,
    DEATH_FLASH_MS: 100,

    COLORS: {
        ALIVE: '#58b66f',
        DEAD: '#171b1a',
        GRID: '#33413d',
        DYING: '#5a2429'
    }
});
